
import Head from 'next/head';
import Image from 'next/image';
import { useGetProductsQuery } from '../redux/sevices/productApi';
import styles from '../styles/Home.module.scss';
import { Home } from './../src/components/Home/Home';



const HomePage: React.FC = () => {
  return (
    <div className={styles.container} style={{backgroundColor:'#f7f7f7'}}>
      <Head>
        <title>Simple Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home/>
    </div>
  );
};

export default HomePage;
